#!/bin/sh
# Build steps used in CentOS CI LTP
# Author: Athmane Madjoudj <athmanem@gmail.com>
# Author: Christoph Galuschka
#	  christoph.galuschka@chello.at

LTPtext='LTP-Testsuite:'

yum -y update
echo "`date +%H:%M:%S` - $LTPtext Installing prerequisite packages"
yum -y groupinstall development
yum -y install autoconf
echo "`date +%H:%M:%S` - $LTPtext running configure"
./configure >/dev/null 2>&1
echo "`date +%H:%M:%S` - $LTPtext running make"
make all >/dev/null
echo "`date +%H:%M:%S` - $LTPtext installing"
make install >/dev/null

echo "`date +%H:%M:%S` - $LTPtext Starting LTP-Lite testsuite"
/opt/ltp/runltplite.sh -l result.txt -p >/dev/null &
tail -f /opt/ltp/results/result.txt

echo "`date +%H:%M:%S` - $LTPtext Number of FAILed tests: "
grep -c FAIL /opt/ltp/results/result.txt

echo "`date +%H:%M:%S` - $LTPtext Tests failed: "
grep FAIL /opt/ltp/results/result.txt

ret_val=$(grep -c FAIL /opt/ltp/results/result.txt)
exit $ret_val
